### ISSUE TITLE
Pick a date and location

### ISSUE THREAD

**Issue by mw44118** [216software/heights-code-hop#1]
These are some candidate locations:
-   Cleveland Heights Library on Lee Road
-   Party center in the back of the Cedar Lee movie theater
-   Coventry Elementary

As for dates, I think we should do something in the Spring, so that people can walk around on Lee Road.

Possible dates:
-   Saturday, April 30th, 2016  **first choice right now**
-   Saturday, May 14th, 2016
-  Saturday, May 21st, 2016

Or any subsequent Saturday.

Nearby events:
-   April 22 through April 24 is NASA's space apps challenge, so I don't want to use that date.
-   The library is not available May 7th.
-   Notacon 2014 happened some time in April, not sure if it happened at all in 2015.  I didn't find a date for 2016.
-   OHTech Tech Week is April 9th through 18th
-   Potentially, next TechPint is Friday, May 6th.  Would be nice to get them to mention us.

**Comment by ajm188** [comment]
[CWRU Commencement](https://www.case.edu/registrar/calendar/) is May 15th, so I doubt you would get many case students if you held it that weekend (myself included).

Outside of that, I am personally fine with any of the other suggested dates. Perhaps @brenns10 - who brought this conference to my attention if I remember correctly - has some input as well. I will also drop a link to this issue in the cleveland tech slack.

**Comment by mw44118** [comment]
Muchas gracias amigo

On Wed, Nov 25, 2015 at 10:09 AM, Andrew Mason notifications@github.com
wrote:

> CWRU Commencement https://www.case.edu/registrar/calendar/ is May 15th,
> so I doubt you would get many case students if you held it that weekend
> (myself included).
> 
> Outside of that, I am personally fine with any of the other suggested
> dates. Perhaps @brenns10 https://github.com/brenns10 - who brought this
> conference to my attention if I remember correctly - has some input as
> well. I will also drop a link to this issue in the cleveland tech slack.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/216software/heights-code-hop/issues/1#issuecomment-159635825
> .

## 

W. Matthew Wilson
partner
216 Software, LLC
matt@216software.com
http://216software.com

**Comment by brenns10** [comment]
According to Cleveland Tech Events calendar:
- [April 30th](http://clevelandtechevents.com/calendar/?ai1ec=action~agenda|exact_date~4-30-2016) is clear
- [May 14th](http://clevelandtechevents.com/calendar/?ai1ec=action~agenda|exact_date~5-14-2016) has a few events that I'm not familiar with (along with CWRU commencement)
- [May 21st](http://clevelandtechevents.com/calendar/?ai1ec=action~agenda|exact_date~5-21-2016) also has a few events I'm not familiar with

Personally I'd prefer April 30th (because I won't be aronud on the 21st), but I'm just one person!

Also, speaking of Cleveland Tech Events, once the date, time, and location are finalized, you'll definitely want to get in contact with sadukie about getting this announced on the website.

**Comment by jrgifford** [comment]
notacon doesn't seem to be a thing anymore, because of funding issues: http://www.notacon.org/1895/the-end-of-an-era/

That being said, I'm fine with any of these dates.

**Comment by mw44118** [comment]
OK, I'm strongly inclined to pick April 30th.  Will let that sit for a while and then make it official.

**Comment by mw44118** [comment]
I reserved the library for April 30th.

**Comment by jrgifford** [comment]
:tada:
